const PDFDocument = require('pdfkit');

/**
 * Generates a styled PDF report and streams it directly to the Express response
 */
const generateConsultationPDF = (res, consultation, transcript, analysis, clientName, astrologerName, specialization) => {
  const doc = new PDFDocument({
    margin: 50,
    size: 'A4'
  });

  // Set response headers for PDF download
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=consultation_report_${consultation._id}.pdf`);

  // Pipe PDF stream to Express response
  doc.pipe(res);

  // Styling Constants (Cosmic Purple theme)
  const primaryColor = '#7C3AED'; // Cosmic Purple
  const secondaryColor = '#D97706'; // Stardust Gold/Amber
  const textColor = '#1E293B'; // Dark Slate
  const mutedTextColor = '#64748B'; // Muted Slate

  // Header Banner
  doc.rect(0, 0, 595.28, 120).fill(primaryColor);
  
  // Title
  doc
    .fillColor('#FFFFFF')
    .font('Helvetica-Bold')
    .fontSize(24)
    .text('COSMIC CONSULTATION REPORT', 50, 45, { align: 'center' });
    
  doc
    .fontSize(10)
    .font('Helvetica-Oblique')
    .text('Personalized AI Astrological Insights & Remedies', 50, 75, { align: 'center' });

  // Metadata Card (Box)
  doc.y = 150;
  doc.x = 50;
  
  doc
    .rect(50, 140, 495, 100)
    .lineWidth(1)
    .stroke('#E2E8F0');
    
  doc
    .fillColor(primaryColor)
    .font('Helvetica-Bold')
    .fontSize(12)
    .text('CONSULTATION DETAILS', 70, 155);

  doc
    .fillColor(textColor)
    .font('Helvetica-Bold')
    .fontSize(10)
    .text('Client Name:', 70, 180)
    .font('Helvetica')
    .text(clientName, 150, 180)
    
    .font('Helvetica-Bold')
    .text('Astrologer:', 70, 195)
    .font('Helvetica')
    .text(astrologerName, 150, 195)
    
    .font('Helvetica-Bold')
    .text('Specialization:', 70, 210)
    .font('Helvetica')
    .text(specialization, 150, 210);

  const dateStr = new Date(consultation.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  doc
    .font('Helvetica-Bold')
    .text('Date:', 330, 180)
    .font('Helvetica')
    .text(dateStr, 400, 180)
    
    .font('Helvetica-Bold')
    .text('Sentiment:', 330, 195)
    .font('Helvetica')
    .text(analysis.sentiment || 'Neutral', 400, 195)
    
    .font('Helvetica-Bold')
    .text('Keywords:', 330, 210)
    .font('Helvetica')
    .text((analysis.keywords || []).slice(0, 3).join(', '), 400, 210);

  // Section: AI Astrological Summary
  doc.y = 270;
  doc
    .fillColor(primaryColor)
    .font('Helvetica-Bold')
    .fontSize(14)
    .text('AI ASTROLOGICAL SUMMARY', 50, doc.y)
    .moveDown(0.5);

  doc
    .rect(50, doc.y, 495, 1)
    .fill(primaryColor);

  doc.y += 10;
  doc
    .fillColor(textColor)
    .font('Helvetica')
    .fontSize(11)
    .text(analysis.summary || 'Summary unavailable.', { align: 'justify', lineGap: 4 })
    .moveDown(2);

  // Section: Astrologer Recommendations & Remedies
  doc
    .fillColor(primaryColor)
    .font('Helvetica-Bold')
    .fontSize(14)
    .text('ASTROLOGER NOTES & REMEDIES', 50, doc.y)
    .moveDown(0.5);

  doc
    .rect(50, doc.y, 495, 1)
    .fill(primaryColor);

  doc.y += 10;
  doc
    .fillColor(textColor)
    .font('Helvetica')
    .fontSize(11)
    .text(consultation.notes || 'No custom remedies provided by the astrologer.', { align: 'justify', lineGap: 4 })
    .moveDown(2);

  // Add a page break for the Transcript
  doc.addPage();

  // Section: Full Consultation Transcript
  doc
    .fillColor(primaryColor)
    .font('Helvetica-Bold')
    .fontSize(14)
    .text('CONSULTATION TRANSCRIPTION', 50, 50)
    .moveDown(0.5);

  doc
    .rect(50, doc.y, 495, 1)
    .fill(primaryColor);

  doc.y += 15;
  doc
    .fillColor(textColor)
    .font('Helvetica-Oblique')
    .fontSize(10)
    .text('The following is a verbatim speech-to-text transcription generated by OpenAI Whisper:', 50, doc.y)
    .moveDown(1);

  doc
    .fillColor(textColor)
    .font('Helvetica')
    .fontSize(10)
    .text(transcript || 'No transcript text available.', { align: 'justify', lineGap: 3 });

  // Footer on each page (using event listener)
  let pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    
    // Header for pages > 0
    if (i > 0) {
      doc
        .fillColor(mutedTextColor)
        .font('Helvetica')
        .fontSize(8)
        .text('Cosmic Consultation Report', 50, 20)
        .text(dateStr, 500, 20, { align: 'right' })
        .rect(50, 32, 495, 0.5)
        .fill('#E2E8F0');
    }

    doc
      .rect(50, 790, 495, 0.5)
      .fill('#E2E8F0');

    doc
      .fillColor(mutedTextColor)
      .font('Helvetica')
      .fontSize(8)
      .text('Disclaimer: Astrological insights are subjective and intended for guidance purposes only.', 50, 800)
      .text(`Page ${i + 1} of ${pages.count}`, 500, 800, { align: 'right' });
  }

  // Finalize PDF
  doc.end();
};

module.exports = {
  generateConsultationPDF
};
